// <auto-generated />
using System;
using LmsApp2.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LmsApp2.Api.Migrations
{
    [DbContext(typeof(LmsDatabaseContext))]
    [Migration("20260126113742_ConfiguredIdentity")]
    partial class ConfiguredIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LmsApp2.Api.Identity.AppRoles", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Identity.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId_InMainTable")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Assignment", b =>
                {
                    b.Property<Guid>("Assignmentid")
                        .HasColumnType("uuid")
                        .HasColumnName("assignmentid");

                    b.Property<Guid?>("Classid")
                        .HasColumnType("uuid")
                        .HasColumnName("classid");

                    b.Property<Guid>("Courseid")
                        .HasColumnType("uuid")
                        .HasColumnName("courseid");

                    b.Property<string>("Coursename")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("coursename");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<Guid?>("Employeeid")
                        .HasColumnType("uuid")
                        .HasColumnName("employeeid");

                    b.Property<decimal?>("Totalmarks")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("totalmarks");

                    b.HasKey("Assignmentid")
                        .HasName("assignments_pkey");

                    b.HasIndex("Classid");

                    b.HasIndex("Courseid");

                    b.HasIndex("Employeeid");

                    b.ToTable("assignments", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Assignmentquestion", b =>
                {
                    b.Property<Guid>("Assignmentquestionid")
                        .HasColumnType("uuid")
                        .HasColumnName("assignmentquestionid");

                    b.Property<Guid?>("Assignmentid")
                        .HasColumnType("uuid")
                        .HasColumnName("assignmentid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Assignmentquestionid")
                        .HasName("assignmentquestion_pkey");

                    b.HasIndex(new[] { "Assignmentid" }, "assignmentquestion_assignmentid_key")
                        .IsUnique();

                    b.ToTable("assignmentquestion", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Assignmentsubmission", b =>
                {
                    b.Property<Guid>("Assignmentsubmissionid")
                        .HasColumnType("uuid")
                        .HasColumnName("assignmentsubmissionid");

                    b.Property<Guid?>("Assignmentid")
                        .HasColumnType("uuid")
                        .HasColumnName("assignmentid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("Marksscored")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("marksscored");

                    b.Property<Guid?>("Studentid")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.HasKey("Assignmentsubmissionid")
                        .HasName("assignmentsubmission_pkey");

                    b.HasIndex("Assignmentid");

                    b.HasIndex("Studentid");

                    b.ToTable("assignmentsubmission", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Class", b =>
                {
                    b.Property<Guid>("Classid")
                        .HasColumnType("uuid")
                        .HasColumnName("classid");

                    b.Property<string>("Classgrade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("classgrade");

                    b.Property<string>("Classsection")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("classsection");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("Schoolid")
                        .HasColumnType("uuid")
                        .HasColumnName("schoolid");

                    b.HasKey("Classid")
                        .HasName("class_pkey");

                    b.HasIndex("Schoolid");

                    b.ToTable("class", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Course", b =>
                {
                    b.Property<Guid>("Courseid")
                        .HasColumnType("uuid")
                        .HasColumnName("courseid");

                    b.Property<string>("Boardordepartment")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("boardordepartment");

                    b.Property<Guid?>("Class")
                        .HasColumnType("uuid");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("character varying(130)");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("Teacher")
                        .HasColumnType("uuid");

                    b.HasKey("Courseid")
                        .HasName("course_pkey");

                    b.HasIndex("Class");

                    b.HasIndex("Teacher");

                    b.ToTable("course", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employee", b =>
                {
                    b.Property<Guid>("Employeeid")
                        .HasColumnType("uuid")
                        .HasColumnName("employeeid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool?>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nationality");

                    b.Property<string>("Religion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("religion");

                    b.Property<Guid?>("Schoolid")
                        .HasColumnType("uuid")
                        .HasColumnName("schoolid");

                    b.HasKey("Employeeid")
                        .HasName("employees_pkey");

                    b.HasIndex("Schoolid");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employeeadditionaldoc", b =>
                {
                    b.Property<Guid>("Documentid")
                        .HasColumnType("uuid")
                        .HasColumnName("documentid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Documentpath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("documentpath");

                    b.Property<string>("Documenttype")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("documenttype");

                    b.Property<Guid?>("Employeeid")
                        .HasColumnType("uuid")
                        .HasColumnName("employeeid");

                    b.HasKey("Documentid")
                        .HasName("employeeadditionaldocs_pkey");

                    b.HasIndex("Employeeid");

                    b.ToTable("employeeadditionaldocs", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employeeattendance", b =>
                {
                    b.Property<Guid>("Attendanceid")
                        .HasColumnType("uuid")
                        .HasColumnName("attendanceid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid?>("Employeeid")
                        .HasColumnType("uuid")
                        .HasColumnName("employeeid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Attendanceid")
                        .HasName("employeeattendance_pkey");

                    b.HasIndex("Employeeid");

                    b.ToTable("employeeattendance", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employeedocument", b =>
                {
                    b.Property<Guid>("Documentid")
                        .HasColumnType("uuid")
                        .HasColumnName("documentid");

                    b.Property<string>("Cnicback")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cnicback");

                    b.Property<string>("Cnicfront")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cnicfront");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("Employeeid")
                        .HasColumnType("uuid")
                        .HasColumnName("employeeid");

                    b.Property<string>("Photo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("photo");

                    b.HasKey("Documentid")
                        .HasName("employeedocuments_pkey");

                    b.HasIndex("Employeeid")
                        .IsUnique();

                    b.ToTable("employeedocuments", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employeefinance", b =>
                {
                    b.Property<Guid>("Financeid")
                        .HasColumnType("uuid")
                        .HasColumnName("financeid");

                    b.Property<decimal?>("Allowances")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("allowances")
                        .HasDefaultValueSql("0");

                    b.Property<decimal>("Basicsalary")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("basicsalary");

                    b.Property<decimal?>("Bonuses")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("bonuses")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("Dueonemployee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("dueonemployee")
                        .HasDefaultValueSql("0");

                    b.Property<Guid?>("Employeeid")
                        .HasColumnType("uuid")
                        .HasColumnName("employeeid");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("month");

                    b.Property<decimal?>("Otherdeductions")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("otherdeductions")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Otherdeductionsreasons")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("otherdeductionsreasons");

                    b.Property<decimal?>("Overtimepay")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("overtimepay")
                        .HasDefaultValueSql("0");

                    b.Property<DateOnly>("Paiddate")
                        .HasColumnType("date")
                        .HasColumnName("paiddate");

                    b.Property<string>("Paidmethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paidmethod");

                    b.Property<decimal?>("Taxdeduction")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("taxdeduction")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Financeid")
                        .HasName("employeefinances_pkey");

                    b.HasIndex("Employeeid");

                    b.ToTable("employeefinances", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Exam", b =>
                {
                    b.Property<Guid>("Examid")
                        .HasColumnType("uuid")
                        .HasColumnName("examid");

                    b.Property<Guid?>("Classid")
                        .HasColumnType("uuid")
                        .HasColumnName("classid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Examdate")
                        .HasColumnType("date")
                        .HasColumnName("examdate");

                    b.Property<string>("Examtype")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("examtype");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("subject");

                    b.Property<Guid?>("Teacherid")
                        .HasColumnType("uuid")
                        .HasColumnName("teacherid");

                    b.Property<decimal?>("Totalmarks")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("totalmarks");

                    b.HasKey("Examid")
                        .HasName("exam_pkey");

                    b.HasIndex("Classid");

                    b.HasIndex("Teacherid");

                    b.ToTable("exam", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Examcontent", b =>
                {
                    b.Property<Guid>("Examcontentid")
                        .HasColumnType("uuid")
                        .HasColumnName("examcontentid");

                    b.Property<string>("Contentpath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contentpath");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("Examid")
                        .HasColumnType("uuid")
                        .HasColumnName("examid");

                    b.HasKey("Examcontentid")
                        .HasName("examcontent_pkey");

                    b.HasIndex("Examid");

                    b.ToTable("examcontent", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Examenrollment", b =>
                {
                    b.Property<Guid>("Enrollmentid")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollmentid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("Examid")
                        .HasColumnType("uuid")
                        .HasColumnName("examid");

                    b.Property<Guid?>("Studentid")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.HasKey("Enrollmentid")
                        .HasName("examenrollments_pkey");

                    b.HasIndex("Examid");

                    b.HasIndex("Studentid");

                    b.ToTable("examenrollments", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Examresult", b =>
                {
                    b.Property<Guid>("Resultid")
                        .HasColumnType("uuid")
                        .HasColumnName("resultid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid?>("Enrollmentid")
                        .HasColumnType("uuid")
                        .HasColumnName("enrollmentid");

                    b.Property<decimal?>("Marksscored")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)")
                        .HasColumnName("marksscored");

                    b.Property<Guid?>("Studentid")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.HasKey("Resultid")
                        .HasName("examresult_pkey");

                    b.HasIndex("Studentid");

                    b.HasIndex(new[] { "Enrollmentid" }, "examresult_enrollmentid_key")
                        .IsUnique();

                    b.ToTable("examresult", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.School", b =>
                {
                    b.Property<Guid>("Schoolid")
                        .HasColumnType("uuid")
                        .HasColumnName("schoolid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Schoolname")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("schoolname");

                    b.HasKey("Schoolid")
                        .HasName("school_pkey");

                    b.HasIndex(new[] { "Schoolname" }, "school_schoolname_key")
                        .IsUnique();

                    b.ToTable("school", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Student", b =>
                {
                    b.Property<Guid>("Studentid")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("Bloodgroup")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("bloodgroup");

                    b.Property<Guid?>("Classid")
                        .HasColumnType("uuid")
                        .HasColumnName("classid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Guardiancontact")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("guardiancontact");

                    b.Property<string>("Guardianname")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("guardianname");

                    b.Property<bool>("Isactive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nationality");

                    b.Property<string>("Religion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("religion");

                    b.Property<Guid?>("Schoolid")
                        .HasColumnType("uuid")
                        .HasColumnName("schoolid");

                    b.HasKey("Studentid")
                        .HasName("students_pkey");

                    b.HasIndex("Classid");

                    b.HasIndex("Schoolid");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Studentadditionaldoc", b =>
                {
                    b.Property<Guid>("Documentid")
                        .HasColumnType("uuid")
                        .HasColumnName("documentid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Documentpath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("documentpath");

                    b.Property<string>("Documenttype")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("documenttype");

                    b.Property<Guid?>("Studentid")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.HasKey("Documentid")
                        .HasName("studentadditionaldocs_pkey");

                    b.HasIndex("Studentid");

                    b.ToTable("studentadditionaldocs", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Studentattendance", b =>
                {
                    b.Property<Guid>("Attendanceid")
                        .HasColumnType("uuid")
                        .HasColumnName("attendanceid");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid?>("Studentid")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.HasKey("Attendanceid")
                        .HasName("studentattendance_pkey");

                    b.HasIndex("Studentid");

                    b.ToTable("studentattendance", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Studentdocument", b =>
                {
                    b.Property<Guid>("Documentid")
                        .HasColumnType("uuid")
                        .HasColumnName("documentid");

                    b.Property<string>("Cnicbackorbform")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cnicbackorbform");

                    b.Property<string>("Cnicfrontorbform")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("cnicfrontorbform");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("photo");

                    b.Property<Guid?>("Studentid")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.HasKey("Documentid")
                        .HasName("studentdocuments_pkey");

                    b.HasIndex(new[] { "Studentid" }, "studentdocuments_studentid_key")
                        .IsUnique();

                    b.ToTable("studentdocuments", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Studentfinance", b =>
                {
                    b.Property<Guid>("Financeid")
                        .HasColumnType("uuid")
                        .HasColumnName("financeid");

                    b.Property<decimal?>("Amountpaid")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amountpaid")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("Amountremaining")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amountremaining")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("Coursefee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("coursefee")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("Examinationfee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("examinationfee")
                        .HasDefaultValueSql("0");

                    b.Property<Guid?>("Issuedby")
                        .HasColumnType("uuid")
                        .HasColumnName("issuedby");

                    b.Property<DateTime?>("Issueddate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("issueddate")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("month");

                    b.Property<decimal?>("Othercharges")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("othercharges")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Otherchargesreasons")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("otherchargesreasons");

                    b.Property<DateOnly?>("Paiddate")
                        .HasColumnType("date")
                        .HasColumnName("paiddate");

                    b.Property<string>("Paidmethod")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("paidmethod");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("remarks");

                    b.Property<Guid?>("Studentid")
                        .HasColumnType("uuid")
                        .HasColumnName("studentid");

                    b.Property<decimal?>("Transportfee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("transportfee")
                        .HasDefaultValueSql("0");

                    b.Property<decimal?>("Tuitionfee")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("tuitionfee")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime?>("Updatedat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updatedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Financeid")
                        .HasName("studentfinances_pkey");

                    b.HasIndex("Issuedby");

                    b.HasIndex("Studentid");

                    b.ToTable("studentfinances", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Assignment", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Class", "Class")
                        .WithMany("Assignments")
                        .HasForeignKey("Classid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("assignments_classid_fkey");

                    b.HasOne("LmsApp2.Api.Models.Course", "Course")
                        .WithMany("Assignments")
                        .HasForeignKey("Courseid")
                        .IsRequired()
                        .HasConstraintName("assignments_courseid_fkey");

                    b.HasOne("LmsApp2.Api.Models.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("Employeeid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("assignments_employeeid_fkey");

                    b.Navigation("Class");

                    b.Navigation("Course");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Assignmentquestion", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Assignment", "Assignment")
                        .WithOne("Assignmentquestion")
                        .HasForeignKey("LmsApp2.Api.Models.Assignmentquestion", "Assignmentid")
                        .HasConstraintName("assignmentquestion_assignmentid_fkey");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Assignmentsubmission", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Assignment", "Assignment")
                        .WithMany("Assignmentsubmissions")
                        .HasForeignKey("Assignmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("assignmentsubmission_assignmentid_fkey");

                    b.HasOne("LmsApp2.Api.Models.Student", "Student")
                        .WithMany("Assignmentsubmissions")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("assignmentsubmission_studentid_fkey");

                    b.Navigation("Assignment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Class", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.School", "School")
                        .WithMany("Classes")
                        .HasForeignKey("Schoolid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("class_schoolid_fkey");

                    b.Navigation("School");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Course", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Class", "ClassNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("Class")
                        .HasConstraintName("course_Class_fkey");

                    b.HasOne("LmsApp2.Api.Models.Employee", "TeacherNavigation")
                        .WithMany("Courses")
                        .HasForeignKey("Teacher")
                        .HasConstraintName("course_Teacher_fkey");

                    b.Navigation("ClassNavigation");

                    b.Navigation("TeacherNavigation");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employee", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.School", "School")
                        .WithMany("Employees")
                        .HasForeignKey("Schoolid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("employees_schoolid_fkey");

                    b.Navigation("School");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employeeadditionaldoc", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Employee", "Employee")
                        .WithMany("Employeeadditionaldocs")
                        .HasForeignKey("Employeeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("employeeadditionaldocs_employeeid_fkey");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employeeattendance", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Employee", "Employee")
                        .WithMany("Employeeattendances")
                        .HasForeignKey("Employeeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("employeeattendance_employeeid_fkey");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employeedocument", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Employee", "Employee")
                        .WithOne("Employeedocuments")
                        .HasForeignKey("LmsApp2.Api.Models.Employeedocument", "Employeeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("employeedocuments_employeeid_fkey");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employeefinance", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Employee", "Employee")
                        .WithMany("Employeefinances")
                        .HasForeignKey("Employeeid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("employeefinances_employeeid_fkey");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Exam", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Class", "Class")
                        .WithMany("Exams")
                        .HasForeignKey("Classid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("exam_classid_fkey");

                    b.HasOne("LmsApp2.Api.Models.Employee", "Teacher")
                        .WithMany("Exams")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("exam_teacherid_fkey");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Examcontent", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Exam", "Exam")
                        .WithMany("Examcontents")
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("examcontent_examid_fkey");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Examenrollment", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Exam", "Exam")
                        .WithMany("Examenrollments")
                        .HasForeignKey("Examid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("examenrollments_examid_fkey");

                    b.HasOne("LmsApp2.Api.Models.Student", "Student")
                        .WithMany("Examenrollments")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("examenrollments_studentid_fkey");

                    b.Navigation("Exam");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Examresult", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Examenrollment", "Enrollment")
                        .WithOne("Examresult")
                        .HasForeignKey("LmsApp2.Api.Models.Examresult", "Enrollmentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("examresult_enrollmentid_fkey");

                    b.HasOne("LmsApp2.Api.Models.Student", "Student")
                        .WithMany("Examresults")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("examresult_studentid_fkey");

                    b.Navigation("Enrollment");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Student", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("Classid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("students_classid_fkey");

                    b.HasOne("LmsApp2.Api.Models.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("Schoolid")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("students_schoolid_fkey");

                    b.Navigation("Class");

                    b.Navigation("School");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Studentadditionaldoc", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Student", "Student")
                        .WithMany("Studentadditionaldocs")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("studentadditionaldocs_studentid_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Studentattendance", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Student", "Student")
                        .WithMany("Studentattendances")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("studentattendance_studentid_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Studentdocument", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Student", "Student")
                        .WithOne("Studentdocument")
                        .HasForeignKey("LmsApp2.Api.Models.Studentdocument", "Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("studentdocuments_studentid_fkey");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Studentfinance", b =>
                {
                    b.HasOne("LmsApp2.Api.Models.Employee", "IssuedbyNavigation")
                        .WithMany("Studentfinances")
                        .HasForeignKey("Issuedby")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("studentfinances_issuedby_fkey");

                    b.HasOne("LmsApp2.Api.Models.Student", "Student")
                        .WithMany("Studentfinances")
                        .HasForeignKey("Studentid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("studentfinances_studentid_fkey");

                    b.Navigation("IssuedbyNavigation");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("LmsApp2.Api.Identity.AppRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("LmsApp2.Api.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("LmsApp2.Api.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("LmsApp2.Api.Identity.AppRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LmsApp2.Api.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("LmsApp2.Api.Identity.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Assignment", b =>
                {
                    b.Navigation("Assignmentquestion");

                    b.Navigation("Assignmentsubmissions");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Class", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Courses");

                    b.Navigation("Exams");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Course", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Employee", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Courses");

                    b.Navigation("Employeeadditionaldocs");

                    b.Navigation("Employeeattendances");

                    b.Navigation("Employeedocuments");

                    b.Navigation("Employeefinances");

                    b.Navigation("Exams");

                    b.Navigation("Studentfinances");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Exam", b =>
                {
                    b.Navigation("Examcontents");

                    b.Navigation("Examenrollments");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Examenrollment", b =>
                {
                    b.Navigation("Examresult");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.School", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Employees");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("LmsApp2.Api.Models.Student", b =>
                {
                    b.Navigation("Assignmentsubmissions");

                    b.Navigation("Examenrollments");

                    b.Navigation("Examresults");

                    b.Navigation("Studentadditionaldocs");

                    b.Navigation("Studentattendances");

                    b.Navigation("Studentdocument");

                    b.Navigation("Studentfinances");
                });
#pragma warning restore 612, 618
        }
    }
}
